# Generated by Django 2.2.9 on 2020-01-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=5)),
                ('order_users', models.IntegerField()),
                ('summonerName', models.CharField(max_length=30)),
                ('user_create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_matches', models.IntegerField()),
                ('match_wl', models.CharField(default='N/A', max_length=4)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.users')),
            ],
        ),
    ]
