# Generated by Django 2.2.9 on 2020-01-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='order_users',
            new_name='userNumber',
        ),
        migrations.AlterField(
            model_name='users',
            name='area',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='summonerName',
            field=models.CharField(max_length=20),
        ),
    ]
